### ISSUE TITLE
💡 Accept different date formats

### ISSUE THREAD

**Issue by zhengruoxin** [AY2021S2-CS2103-W16-3/tp#91]
### Describe the issue
*What is the problem, if any? What is the desired behavior?*

Birthday dates are currently accepted only in yyyy-mm-dd format. 
Might want to allow other input formats such as dd-mm-yyyy / allow inputs without year too.

________________________________________________________________
### Additional context
*Describe possible and/or alternative solutions, to highlight required scope of work.*

<img width="360" alt="Screenshot 2021-03-11 at 19 25 44" src="https://user-images.githubusercontent.com/65821483/110780915-36298100-82a0-11eb-8e45-ac8cf933c42b.png">
<img width="358" alt="Screenshot 2021-03-11 at 19 32 00" src="https://user-images.githubusercontent.com/65821483/110781118-7688ff00-82a0-11eb-8aa1-e6590a9533b8.png">
<img width="380" alt="Screenshot 2021-03-11 at 19 32 46" src="https://user-images.githubusercontent.com/65821483/110781205-93253700-82a0-11eb-9fcf-ea39b2ba97ea.png">

**Comment by garyljj** [comment]
Actually, since year not really important for a birthday, maybe we can store it in a [MonthDay ](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/MonthDay.html) object instead. Then no need request year input at all.

**Comment by zhengruoxin** [comment]
The year can be useful to remember a friend's age though, so you won't eg. accidentally wish your friend. "Happy 21st" when it's their 22nd.

**Comment by garyljj** [comment]
Perhaps can also change display of bday in a form of "11 Dec 99" instead of the current 1999-12-11.

**Comment by pyuxiang** [comment]
Personally I'd avoid the highly ambiguous "11 Dec 02", partly because it's uncommon, and will silently succeed for international users whose local formats follow "yy/mm/dd" instead of "dd/mm/yy". Perhaps enforcing the "yyyy" format will catch potential errors, or another option would be to allow users to customize the desired date format.

This might be a good reference: https://en.wikipedia.org/wiki/Date_format_by_country

Perhaps the formats we might want to support include:

- "yyyy-mm-dd" ISO-8601
- "d.m.yyyy" German
- "d/m/yyyy" French

with the associated long forms:

- "mmm d yyyy" USA (+ "mmmm d yyyy")
- "d mmm yyyy" Singapore (+ "d mmmm yyyy")
